root: true

parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"

extends:
  - "airbnb"
  - "airbnb/hooks"
  - "airbnb-typescript"
  - "prettier"

plugins:
  - "import"
  - "unused-imports"
  - "@typescript-eslint"

rules:
  import/prefer-default-export: "off"
  import/no-extraneous-dependencies: "off"
  react/react-in-jsx-scope: "off"
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
        - object
        - type
        - index
      newlines-between: "always"
      alphabetize:
        order: "asc"
        caseInsensitive: true
  unused-imports/no-unused-imports: "warn"

overrides:
  - files: ["src/nodecg/*.ts"]
    rules:
      "@typescript-eslint/no-unused-vars": "off"
